// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEjJihevtVX4n_7k36M5GbwZd-qUVS6Dc',
    appId: '1:82312839239:web:af630e97dde269133a7162',
    messagingSenderId: '82312839239',
    projectId: 'deplight-softbank',
    authDomain: 'deplight-softbank.firebaseapp.com',
    storageBucket: 'deplight-softbank.firebasestorage.app',
    measurementId: 'G-SEE40VG6SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtj-ovIZO1uDOzUuQUYIBLLwKE_DyntlM',
    appId: '1:82312839239:android:89abba52bc8137d43a7162',
    messagingSenderId: '82312839239',
    projectId: 'deplight-softbank',
    storageBucket: 'deplight-softbank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXs0G0W1lB7FmzrF_svQ2mT-Oy4_cK4k',
    appId: '1:82312839239:ios:1ce28159c7995b893a7162',
    messagingSenderId: '82312839239',
    projectId: 'deplight-softbank',
    storageBucket: 'deplight-softbank.firebasestorage.app',
    iosClientId: '82312839239-vej7l61c68tt4a6n9hfd5puo34h878a1.apps.googleusercontent.com',
    iosBundleId: 'com.deplight.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFXs0G0W1lB7FmzrF_svQ2mT-Oy4_cK4k',
    appId: '1:82312839239:ios:1ce28159c7995b893a7162',
    messagingSenderId: '82312839239',
    projectId: 'deplight-softbank',
    storageBucket: 'deplight-softbank.firebasestorage.app',
    iosClientId: '82312839239-vej7l61c68tt4a6n9hfd5puo34h878a1.apps.googleusercontent.com',
    iosBundleId: 'com.deplight.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEjJihevtVX4n_7k36M5GbwZd-qUVS6Dc',
    appId: '1:82312839239:web:73ea53ec819e272e3a7162',
    messagingSenderId: '82312839239',
    projectId: 'deplight-softbank',
    authDomain: 'deplight-softbank.firebaseapp.com',
    storageBucket: 'deplight-softbank.firebasestorage.app',
    measurementId: 'G-6X1ZCHTGME',
  );
}
